version: '3.1'

services:
    mtrad:
        container_name: mtrad
        image: mtradumatica:latest
        ports:
            - "5000:5000"
            - "10000:10000"
            - "8000:8000"
        networks:
            - mtrad
        volumes:
            - .:/opt/mtradumatica
        deploy:
            resources:
                reservations:
                    memory: 6G

networks:
    mtrad: