# -*- coding: utf-8 -*-

lang_select_list = [(u"af", u"Afrikaans"),        (u"sq", u"Shqip"),           (u"am", u"አማርኛ"),             (u"ar", u"العربية"), 
                    (u"an", u"Aragonés"),         (u"hy", u"Հայերեն"),         (u"ae", u"Avesta"),           (u"ay", u"Aymar aru"), 
                    (u"az", u"Azərbaycan dili"),  (u"eu", u"Euskara"),         (u"be", u"Беларуская мова"),  (u"bi", u"Bislama"), 
                    (u"bs", u"Bosanski"),         (u"br", u"Brezhoneg"),       (u"bg", u"Български език"),   (u"ca", u"Català"), 
                    (u"ce", u"Нохчийн мотт"),     (u"ny", u"ChiCheŵa"),        (u"zh", u"中文"),             (u"cv", u"Чӑваш чӗлхи"), 
                    (u"co", u"Corsu"),            (u"hr", u"Hrvatski"),        (u"cs", u"Čeština"),          (u"da", u"Dansk"), 
                    (u"nl", u"Nederlands"),       (u"en", u"English"),         (u"eo", u"Esperanto"),        (u"et", u"Eesti"), 
                    (u"ee", u"Eʋegbe"),           (u"fo", u"Føroyskt"),        (u"fj", u"Vosa Vakaviti"),    (u"fi", u"Suomi"), 
                    (u"fr", u"Français"),         (u"gl", u"Galego"),          (u"ka", u"ქართული"),          (u"de", u"Deutsch"), 
                    (u"el", u"Ελληνικά"),         (u"gn", u"Avañe'ẽ"),         (u"gu", u"ગુજરાતી"),           (u"he", u"עברית"), 
                    (u"hi", u"हिन्दी"),             (u"hu", u"Magyar"),          (u"id", u"Bahasa Indonesia"), (u"ga", u"Gaeilge"),
                    (u"is", u"Íslenska"),         (u"it", u"Italiano"),        (u"ja", u"日本語"),           (u"jv", u"Basa Jawa"), 
                    (u"kk", u"Қазақ тілі"),       (u"ky", u"Кыргызча"),        (u"kv", u"Коми кыв"),         (u"kg", u"Kikongo"), 
                    (u"kj", u"Kuanyama"),         (u"la", u"Latine"),          (u"lg", u"Luganda"),          (u"ln", u"Lingála"),
                    (u"lo", u"ພາສາລາວ"),          (u"lt", u"Lietuvių kalba"),  (u"lv", u"Latviešu valoda"),  (u"gv", u"Gaelg"), 
                    (u"mk", u"Македонски јазик"), (u"mg", u"Fiteny malagasy"), (u"ml", u"മലയാളം"),           (u"mt", u"Malti"), 
                    (u"mi", u"Te reo Māori"),     (u"mn", u"Монгол хэл"),      (u"nv", u"Diné bizaad"),      (u"nd", u"IsiNdebele"), 
                    (u"ne", u"नेपाली"),            (u"ng", u"Owambo"),          (u"nb", u"Norsk bokmål"),     (u"nn", u"Norsk nynorsk"), 
                    (u"nr", u"IsiNdebele"),       (u"oc", u"Occitan"),         (u"fa", u"فارسی"),            (u"pl", u"Język polski"), 
                    (u"ps", u"پښتو"),             (u"pt", u"Português"),       (u"qu", u"Runa Simi"),        (u"rm", u"Rumantsch grischun"), 
                    (u"rn", u"Ikirundi"),         (u"ro", u"Română"),          (u"ru", u"Русский"),          (u"sa", u"संस्कृतम्"),
                    (u"sc", u"Sardu"),            (u"sr", u"Српски"),          (u"gd", u"Gàidhlig"),         (u"sn", u"ChiShona"), 
                    (u"si", u"සිංහල"),             (u"sk", u"Slovenčina"),      (u"sl", u"Slovenski"),        (u"so", u"Soomaaliga"), 
                    (u"st", u"Sesotho"),          (u"es", u"Español"),         (u"su", u"Basa Sunda"),       (u"sw", u"Kiswahili"), 
                    (u"ss", u"SiSwati"),          (u"sv", u"Svenska"),         (u"ta", u"தமிழ்"),              (u"te", u"తెలుగు"),
                    (u"th", u"ไทย"),              (u"bo", u"བོད་ཡིག"),           (u"tl", u"Wikang Tagalog"),   (u"tn", u"Setswana"), 
                    (u"to", u"Faka Tonga"),       (u"tr", u"Türkçe"),          (u"ts", u"Xitsonga"),         (u"tw", u"Twi"), 
                    (u"uk", u"Українська мова"),  (u"ur", u"اردو"),            (u"ve", u"Tshivenḓa"),        (u"vi", u"Tiếng Việt"), 
                    (u"cy", u"Cymraeg"),          (u"wo", u"Wollof"),          (u"fy", u"Frysk"),            (u"xh", u"IsiXhosa"), 
                    (u"yi", u"ייִדיש"),            (u"yo", u"Yorùbá"),          (u"zu", u"IsiZulu")]
