# -*- coding: utf-8 -*-

lang_select_list = [(u"ae", u"Avesta"),
(u"af", u"Afrikaans"),
(u"am", u"አማርኛ"),
(u"an", u"Aragonés"),
(u"ar", u"العربية"),
(u"ay", u"Aymar aru"),
(u"az", u"Azərbaycan dili"),
(u"be", u"Беларуская"),
(u"bg", u"Български"),
(u"bi", u"Bislama"),
(u"bo", u"བོད་ཡིག"),
(u"br", u"Brezhoneg"),
(u"bs", u"Bosanski"),
(u"ca", u"Català"),
(u"ce", u"Нохчийн мотт"),
(u"co", u"Corsu"),
(u"cs", u"Čeština"),
(u"cv", u"Чӑваш чӗлхи"),
(u"cy", u"Cymraeg"),
(u"da", u"Dansk"),
(u"de", u"Deutsch"),
(u"ee", u"Eʋegbe"),
(u"el", u"Ελληνικά"),
(u"en", u"English"),
(u"eo", u"Esperanto"),
(u"es", u"Español"),
(u"et", u"Eesti"),
(u"eu", u"Euskara"),
(u"fa", u"فارسی"),
(u"fi", u"Suomi"),
(u"fj", u"Vosa Vakaviti"),
(u"fo", u"Føroyskt"),
(u"fr", u"Français"),
(u"fy", u"Frysk"),
(u"ga", u"Gaeilge"),
(u"gd", u"Gàidhlig"),
(u"gl", u"Galego"),
(u"gn", u"Avañe'ẽ"),
(u"gu", u"ગુજરાતી"),
(u"gv", u"Gaelg"),
(u"he", u"עברית"),
(u"hi", u"हिन्दी"),
(u"hr", u"Hrvatski"),
(u"hu", u"Magyar"),
(u"hy", u"Հայերեն"),
(u"id", u"Bahasa Indonesia"),
(u"is", u"Íslenska"),
(u"it", u"Italiano"),
(u"ja", u"日本語"),
(u"jv", u"Basa Jawa"),
(u"ka", u"ქართული"),
(u"kg", u"Kikongo"),
(u"kj", u"Kuanyama"),
(u"kk", u"Қазақ тілі"),
(u"ku", u"Kurdî"),
(u"kv", u"Коми кыв"),
(u"ky", u"Кыргызча"),
(u"la", u"Latine"),
(u"ln", u"Lingála"),
(u"lo", u"ພາສາລາວ"),
(u"lt", u"Lietuvių kalba"),
(u"lv", u"Latviešu valoda"),
(u"mg", u"Fiteny malagasy"),
(u"mi", u"Te reo Māori"),
(u"mk", u"Македонски јазик"),
(u"ml", u"മലയാളം"),
(u"mn", u"Монгол хэл"),
(u"mt", u"Malti"),
(u"nb", u"Norsk bokmål"),
(u"nd", u"IsiNdebele"),
(u"ne", u"नेपाली"),
(u"ng", u"Owambo"),
(u"nl", u"Nederlands"),
(u"nn", u"Norsk nynorsk"),
(u"nr", u"IsiNdebele"),
(u"nv", u"Diné bizaad"),
(u"ny", u"ChiCheŵa"),
(u"oc", u"Occitan"),
(u"pl", u"Język polski"),
(u"ps", u"پښتو"),
(u"pt", u"Português"),
(u"qu", u"Runa Simi"),
(u"rm", u"Rumantsch grischun"),
(u"rn", u"Ikirundi"),
(u"ro", u"Română"),
(u"ru", u"Русский"),
(u"sa", u"संस्कृतम्"),
(u"sc", u"Sardu"),
(u"si", u"සිංහල"),
(u"sk", u"Slovenčina"),
(u"sl", u"Slovenski"),
(u"sn", u"ChiShona"),
(u"so", u"Soomaaliga"),
(u"sq", u"Shqip"),
(u"sr", u"Српски"),
(u"ss", u"SiSwati"),
(u"st", u"Sesotho"),
(u"su", u"Basa Sunda"),
(u"sv", u"Svenska"),
(u"sw", u"Kiswahili"),
(u"ta", u"தமிழ்"),
(u"te", u"తెలుగు"),
(u"th", u"ไทย"),
(u"tl", u"Wikang Tagalog"),
(u"tn", u"Setswana"),
(u"to", u"Faka Tonga"),
(u"tr", u"Türkçe"),
(u"ts", u"Xitsonga"),
(u"tw", u"Twi"),
(u"uk", u"Українська мова"),
(u"ur", u"اردو"),
(u"ve", u"Tshivenḓa"),
(u"vi", u"Tiếng Việt"),
(u"wo", u"Wollof"),
(u"xh", u"IsiXhosa"),
(u"yi", u"ייִדיש"),
(u"yo", u"Yorùbá"),
(u"zh", u"中文"),
(u"zu", u"IsiZulu")]
